import {
  Activity,
  Archive,
  Bell,
  BookOpen,
  Boxes,
  Bug,
  Calendar,
  Camera,
  Clapperboard,
  Clock,
  Cloud,
  Code,
  Container,
  Cpu,
  Database,
  Download,
  Film,
  Fingerprint,
  Folder,
  Gamepad2,
  Gauge,
  GitBranch,
  Globe,
  HardDrive,
  Home,
  Image,
  KeyRound,
  Lightbulb,
  Lock,
  Mail,
  MessageSquare,
  Music,
  Network,
  Plug,
  Printer,
  Rss,
  Router,
  Server,
  Settings,
  Shield,
  Terminal,
  Thermometer,
  Tv,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/** Curated homelab icon set — keys are stored in links.json (icon.name). */
export const ICONS: Record<string, LucideIcon> = {
  server: Server,
  database: Database,
  "hard-drive": HardDrive,
  cpu: Cpu,
  boxes: Boxes,
  container: Container,
  network: Network,
  router: Router,
  wifi: Wifi,
  globe: Globe,
  cloud: Cloud,
  shield: Shield,
  lock: Lock,
  key: KeyRound,
  fingerprint: Fingerprint,
  home: Home,
  lightbulb: Lightbulb,
  thermometer: Thermometer,
  plug: Plug,
  zap: Zap,
  film: Film,
  clapperboard: Clapperboard,
  music: Music,
  tv: Tv,
  gamepad: Gamepad2,
  camera: Camera,
  image: Image,
  download: Download,
  folder: Folder,
  archive: Archive,
  book: BookOpen,
  rss: Rss,
  mail: Mail,
  message: MessageSquare,
  calendar: Calendar,
  clock: Clock,
  activity: Activity,
  gauge: Gauge,
  bell: Bell,
  terminal: Terminal,
  code: Code,
  git: GitBranch,
  bug: Bug,
  printer: Printer,
  settings: Settings,
  wrench: Wrench,
};

export const ICON_NAMES = Object.keys(ICONS);
